### ISSUE TITLE
db.close() promise does not reliably resolve on yieldb 2.3

### ISSUE THREAD

**Issue by jlai** [pebble/yieldb#11]
Sometimes db.close() does not resolve its promise after closing the database connection. The issue appears to be in helper.makeThen; if the promise is resolved immediately, the line `promise = resolve = reject = fn = null;` nulls out promise/resolve/reject right before trying to call `return promise.then(resolve, reject)`

For example, this never prints "done":

```js
var co = require('co');
var yieldb = require('yieldb');

co(function* () {
  var db = yield yieldb.connect('mongodb://localhost/test');
  yield db.close();
}).then(function () {
  console.log('done');
}, function (err) {
  console.error(err);
});
```

**Comment by aheckmann** [comment]
Interesting. I couldn't reproduce until I reinstalled all dependencies so something underneath has changed behavior. Will investigate further.

**Comment by aheckmann** [comment]
theres a [bug in the upstream mongo driver](https://jira.mongodb.org/browse/NODE-463) which immediately executes the callback passed to `db.close(cb)`. fixed here for now.
