### ISSUE TITLE
installing on iojs

### ISSUE THREAD

**Issue by bitinn** [pebble/yieldb#15]
My investigation seems to suggest `yieldb`, or any module that depends on mongodb driver 1.4.x, is not able to build c++ bson driver anymore.

Not a `yieldb` issue per se, but sharing it as a heads-up (and hopefully I wasn't mistaken).

https://github.com/mongodb/js-bson/issues/136

**Comment by aheckmann** [comment]
good catch! thanks for the heads up and for pushing that forward.

**Comment by bitinn** [comment]
Issue is now fixed, `npm update yieldb` will compile a working bson driver.
