### ISSUE TITLE
Eventually move onto returning promise consistently

### ISSUE THREAD

**Issue by bitinn** [pebble/yieldb#3]
Let me prefix this by stating there isn't an emergency for this change, but I consider it a good direction in the long run (ie. v3), since we are using `yieldb` on a new project, might as well plan for it.

My question: for those APIs returning thunk, are they chosen based on semantic reason or performance reason? Since `yieldb` assumes node v0.11, I guess it's not due to compatibility?

There are many debates around whether `co` should continue to support thunk, given it's moving towards ES7 async/await, which support promise only. But perhaps the larger gain here is not needing to specify if an API is returning thunk or promise.

And I prefer to use `then/catch` instead of node style callback when not using `co`, but that's my personal preference.

**Comment by bitinn** [comment]
Not sure about the easier to implement part, since most of the queries are already promise-based. Maybe some find it easier to explain what `thunks` do than `promises`.

> supports apis like .aggregate().stream() which would not be possible using an approach which immediately executes the query (like promises)

Understand this is a general problem as one needs to choose between Promise and Stream, but perhaps we can provide a method/options to enable optional piping.

> cannot use a chaining api for streams because query is immediately executed

mquery seems to does chaining just fine by creating a thenable function?

For common actions like `insert` I don't see many advantages of thunk over promise, maybe I missed something?

**Comment by aheckmann** [comment]
i agree with the goal of making the return objects all thenables for maximum interop. haven't thought a lot about it yet but one possibility is just adding a `then()` method to the thunks.

**Comment by aheckmann** [comment]
try out 2.3.0 and let me know if this works for you. every method now returns something which has a `then()` method and is therefore a Promise.

**Comment by bitinn** [comment]
amazing, i will try it out.
