### ISSUE TITLE
Quick question: why set fullResult: true by default

### ISSUE THREAD

**Issue by bitinn** [pebble/yieldb#6]
My guess is you need the actual server response for some reasons? I am not sure why they are preferred over `_id` in yieldb's case.

```
// fullResult: true
{ ok: 1,
  writeErrors: [],
  writeConcernErrors: [],
  nInserted: 2,
  nUpserted: 0,
  nMatched: 0,
  nModified: 0,
  nRemoved: 0,
  upserted: [] }
```

```
// fullResult: false
[ { a: 1, _id: 54acc0b7fbae36540d280052 },
  { b: 1, _id: 54acc0b7fbae36540d280053 } 
```

**Comment by aheckmann** [comment]
I don't pretend to know what everyone does with this info but exposing all
of it vs a tiny subset opens doors to more possibilities and future proofs
things. In fact, the latest release of the driver is doing the same thing
now. As for me personally, it's needed in cases where you need to know if
the upsert resulted in an insert vs update or determining how many objects
were removed etc. New driver includes the _id as well which we'll move to
at some point

On Tuesday, January 6, 2015, David Frank <notifications@github.com> wrote:

> My guess is you need the actual server response for some reasons? I am not
> sure why they are preferred over _id in yieldb's case.
>
> // fullResult: true
> { ok: 1,
>   writeErrors: [],
>   writeConcernErrors: [],
>   nInserted: 2,
>   nUpserted: 0,
>   nMatched: 0,
>   nModified: 0,
>   nRemoved: 0,
>   upserted: [] }
>
> // fullResult: false
> [ { a: 1, _id: 54acc0b7fbae36540d280052 },
>   { b: 1, _id: 54acc0b7fbae36540d280053 }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pebble/yieldb/issues/6>.
>


-- 
Aaron Heckmann
Web Development Lead :: Pebble
https://github.com/aheckmann
https://twitter.com/aaronheckmann

**Comment by bitinn** [comment]
cool, no problem
